---
- name: Variables Demo
  hosts: g1
  become: yes
  vars:
    myusername: Cyndodo

  tasks:
  - name: Update Dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynam.html
...